/**
 * CallTest V1 Shared Domain Enums - Phase 8
 */

export enum UserRole {
  DEVELOPER = "DEVELOPER",
  TESTER = "TESTER",
  BOTH = "BOTH",
  ADMIN = "ADMIN",
}

export enum UserStatus {
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  BANNED = "BANNED",
  DELETED = "DELETED",
}

export enum AppPlatform {
  ANDROID = "ANDROID",
}

export enum AppStatus {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  PUBLIC = "PUBLIC",
  ARCHIVED = "ARCHIVED",
  SUSPENDED = "SUSPENDED",
}

export enum CampaignStatus {
  DRAFT = "DRAFT",
  READY = "READY",
  ACTIVE = "ACTIVE",
  TESTING = "TESTING",
  COMPLETED = "COMPLETED",
  PUBLIC = "PUBLIC",
  PAUSED = "PAUSED",
  CANCELLED = "CANCELLED",
  SUSPENDED = "SUSPENDED",
  ENDED_EARLY = "ENDED_EARLY",
  AT_RISK = "AT_RISK",
}

export enum CampaignRisk {
  HEALTHY = "HEALTHY",
  WARNING = "WARNING",
  AT_RISK = "AT_RISK",
  CRITICAL = "CRITICAL",
}

export enum TesterAssignmentType {
  PRIMARY = "PRIMARY",
  PROTECTION = "PROTECTION",
  REPLACEMENT = "REPLACEMENT",
  CORE_TESTER = "CORE_TESTER",
  RELIABLE_REINFORCEMENT = "RELIABLE_REINFORCEMENT",
  BACKUP = "BACKUP",
}

export enum TesterReliabilityTier {
  LOW = "LOW",
  STANDARD = "STANDARD",
  RELIABLE = "RELIABLE",
  HIGHLY_RELIABLE = "HIGHLY_RELIABLE",
}

export enum BackupTesterStatus {
  AVAILABLE = "AVAILABLE",
  RESERVED = "RESERVED",
  ACTIVATED = "ACTIVATED",
  RELEASED = "RELEASED",
}

export enum ScheduledMissionStatus {
  PENDING = "PENDING",
  AVAILABLE = "AVAILABLE",
  COMPLETED = "COMPLETED",
  MISSED = "MISSED",
  EXPIRED = "EXPIRED",
  SKIPPED = "SKIPPED",
  CANCELLED = "CANCELLED",
  BLOCKED_BY_AVAILABILITY = "BLOCKED_BY_AVAILABILITY",
}

export enum AppAvailabilityStatus {
  OPEN = "OPEN",
  AWAITING_DEVELOPER_EVIDENCE = "AWAITING_DEVELOPER_EVIDENCE",
  UNDER_REVIEW = "UNDER_REVIEW",
  AVAILABLE = "AVAILABLE",
  RESTRICTED = "RESTRICTED",
  UNVERIFIED = "UNVERIFIED",
  RESOLVED = "RESOLVED",
  DISMISSED = "DISMISSED",
}

export enum AvailabilityIssueType {
  COUNTRY_RESTRICTION = "COUNTRY_RESTRICTION",
  DEVICE_COMPATIBILITY = "DEVICE_COMPATIBILITY",
  PLAY_STORE_ERROR = "PLAY_STORE_ERROR",
  ACCOUNT_RESTRICTION = "ACCOUNT_RESTRICTION",
  UNKNOWN = "UNKNOWN",
}

export enum AvailabilityScope {
  WORLDWIDE = "WORLDWIDE",
  REGIONAL = "REGIONAL",
}

export enum AvailabilityEvidenceType {
  GOOGLE_PLAY_CONSOLE_SCREENSHOT = "GOOGLE_PLAY_CONSOLE_SCREENSHOT",
  ADDITIONAL_DOCUMENTATION = "ADDITIONAL_DOCUMENTATION",
}

export enum MissionType {
  INSTALL = "INSTALL",
  OPEN = "OPEN",
  EXPLORE = "EXPLORE",
  FUNCTIONAL = "FUNCTIONAL",
  STABILITY = "STABILITY",
  REPORT = "REPORT",
  FINAL_FEEDBACK = "FINAL_FEEDBACK",
}

export enum TesterStatus {
  INVITED = "INVITED",
  ACTIVE = "ACTIVE",
  LOW_ACTIVITY = "LOW_ACTIVITY",
  ABANDONED = "ABANDONED",
  COMPLETED = "COMPLETED",
  REMOVED = "REMOVED",
}

export enum TesterExposureLevel {
  NEW = "NEW",
  PROBATION = "PROBATION",
  ESTABLISHED = "ESTABLISHED",
  HIGH_PERFORMER = "HIGH_PERFORMER",
}

export enum MissionDifficulty {
  EASY = "EASY",
  MEDIUM = "MEDIUM",
  HARD = "HARD",
}

export enum MissionStatus {
  DRAFT = "DRAFT",
  PENDING_REVIEW = "PENDING_REVIEW",
  APPROVED = "APPROVED",
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  COMPLETED = "COMPLETED",
  REJECTED = "REJECTED",
}

export enum AttemptStatus {
  AVAILABLE = "AVAILABLE",
  STARTED = "STARTED",
  SUBMITTED = "SUBMITTED",
  VALIDATED = "VALIDATED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
}

export enum ValidationMethod {
  MANUAL = "MANUAL",
  EVENT = "EVENT",
  CHECKLIST = "CHECKLIST",
  SDK_EVENT = "SDK_EVENT",
  SCREEN_FLOW = "SCREEN_FLOW",
  HYBRID = "HYBRID",
}

export enum MissionQualityRating {
  TOO_COMPLEX = "TOO_COMPLEX",
  CONFUSING = "CONFUSING",
  BROKEN = "BROKEN",
  TOO_LONG = "TOO_LONG",
  UNCLEAR = "UNCLEAR",
  GOOD = "GOOD",
}

export enum ActivityEventType {
  APP_OPENED = "APP_OPENED",
  APP_CLOSED = "APP_CLOSED",
  SESSION_STARTED = "SESSION_STARTED",
  SESSION_ENDED = "SESSION_ENDED",
  SCREEN_VIEW = "SCREEN_VIEW",
  USER_INTERACTION = "USER_INTERACTION",
  MISSION_STARTED = "MISSION_STARTED",
  MISSION_SUBMITTED = "MISSION_SUBMITTED",
  MISSION_COMPLETED = "MISSION_COMPLETED",
  FEEDBACK_SUBMITTED = "FEEDBACK_SUBMITTED",
  BUG_REPORTED = "BUG_REPORTED",
}

export enum ActivityState {
  ACTIVE = "ACTIVE",
  LOW_ACTIVITY = "LOW_ACTIVITY",
  ABANDONED = "ABANDONED",
}

export enum TrustRank {
  NEW = "NEW",
  TRUSTED = "TRUSTED",
  RELIABLE = "RELIABLE",
  EXCELLENT = "EXCELLENT",
  RESTRICTED = "RESTRICTED",
}

export enum FraudSeverity {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum ReputationStatus {
  NORMAL = "NORMAL",
  WATCH = "WATCH",
  RESTRICTED = "RESTRICTED",
  SUSPENDED = "SUSPENDED",
  BANNED = "BANNED",
}

export enum FraudEventType {
  DUPLICATE_EVENT = "DUPLICATE_EVENT",
  CLOCK_MANIPULATION = "CLOCK_MANIPULATION",
  IMPOSSIBLE_SESSION = "IMPOSSIBLE_SESSION",
  RAPID_MISSION_COMPLETION = "RAPID_MISSION_COMPLETION",
  ABNORMAL_MISSION_PATTERN = "ABNORMAL_MISSION_PATTERN",
  REPEATED_ASSIGNMENT_ABUSE = "REPEATED_ASSIGNMENT_ABUSE",
  MULTIPLE_ACCOUNT_SIGNAL = "MULTIPLE_ACCOUNT_SIGNAL",
  SUSPICIOUS_ACTIVITY_BURST = "SUSPICIOUS_ACTIVITY_BURST",
  REPEATED_EVIDENCE_HASH = "REPEATED_EVIDENCE_HASH",
  EVIDENCE_REUSE_ACROSS_CAMPAIGNS = "EVIDENCE_REUSE_ACROSS_CAMPAIGNS",
  EXCESSIVE_REJECTED_EVIDENCE = "EXCESSIVE_REJECTED_EVIDENCE",
  IMPOSSIBLE_EVIDENCE_PATTERN = "IMPOSSIBLE_EVIDENCE_PATTERN",
  RAPID_CLAIM_WITHOUT_PARTICIPATION = "RAPID_CLAIM_WITHOUT_PARTICIPATION",
}

export enum TrustEventType {
  INITIAL_ASSIGNMENT = "INITIAL_ASSIGNMENT",
  CAMPAIGN_COMPLETED = "CAMPAIGN_COMPLETED",
  MISSION_VALIDATED = "MISSION_VALIDATED",
  RECOVERY_BONUS = "RECOVERY_BONUS",
  PENALTY_APPLIED = "PENALTY_APPLIED",
  MANUAL_OVERRIDE = "MANUAL_OVERRIDE",
}

export enum TrustPenaltyType {
  CAMPAIGN_ABANDONMENT = "CAMPAIGN_ABANDONMENT",
  FRAUD_SIGNAL = "FRAUD_SIGNAL",
  REPEATED_SUSPICIOUS_ACTIVITY = "REPEATED_SUSPICIOUS_ACTIVITY",
  INVALID_MISSION_BEHAVIOR = "INVALID_MISSION_BEHAVIOR",
  ACCOUNT_ABUSE = "ACCOUNT_ABUSE",
}

export enum FraudDecisionAction {
  NO_ACTION = "NO_ACTION",
  MONITOR = "MONITOR",
  FLAG = "FLAG",
  RESTRICT = "RESTRICT",
  SUSPEND = "SUSPEND",
  BAN = "BAN",
}

export enum RewardType {
  XP = "XP",
  GOLD = "GOLD",
  COMBINED = "COMBINED",
}

export enum RewardStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum RewardSource {
  MISSION_VALIDATED = "MISSION_VALIDATED",
  MISSION_COMPLETED = "MISSION_COMPLETED",
  FEEDBACK_SUBMITTED = "FEEDBACK_SUBMITTED",
  USEFUL_FEEDBACK = "USEFUL_FEEDBACK",
  CAMPAIGN_PARTICIPATION_COMPLETED = "CAMPAIGN_PARTICIPATION_COMPLETED",
  CAMPAIGN_COMPLETED = "CAMPAIGN_COMPLETED",
  VALID_BUG_REPORT = "VALID_BUG_REPORT",
  EXCELLENT_REPLACEMENT = "EXCELLENT_REPLACEMENT",
}

export enum NotificationStatus {
  PENDING = "PENDING",
  SENT = "SENT",
  DELIVERED = "DELIVERED",
  READ = "READ",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}

export enum NotificationPriority {
  LOW = "LOW",
  NORMAL = "NORMAL",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum NotificationChannel {
  IN_APP = "IN_APP",
  PUSH = "PUSH",
  EMAIL = "EMAIL",
}

export enum NotificationType {
  TESTER_CAMPAIGN_AVAILABLE = "TESTER_CAMPAIGN_AVAILABLE",
  TESTER_MISSION_AVAILABLE = "TESTER_MISSION_AVAILABLE",
  MISSION_COMPLETED = "MISSION_COMPLETED",
  MISSION_REMINDER = "MISSION_REMINDER",
  CAMPAIGN_REMINDER = "CAMPAIGN_REMINDER",
  CAMPAIGN_COMPLETED = "CAMPAIGN_COMPLETED",
  CAMPAIGN_PARTICIPATION_THANK_YOU = "CAMPAIGN_PARTICIPATION_THANK_YOU",
  CAMPAIGN_REPLACEMENT = "CAMPAIGN_REPLACEMENT",
  CAMPAIGN_LOW_ACTIVITY = "CAMPAIGN_LOW_ACTIVITY",
  CAMPAIGN_HEALTH_WARNING = "CAMPAIGN_HEALTH_WARNING",
  CAMPAIGN_HEALTH_CRITICAL = "CAMPAIGN_HEALTH_CRITICAL",
  NEW_TESTER_ASSIGNED = "NEW_TESTER_ASSIGNED",
  TESTER_LOW_ACTIVITY = "TESTER_LOW_ACTIVITY",
  TESTER_ABANDONED = "TESTER_ABANDONED",
  TESTER_REPLACEMENT_ASSIGNED = "TESTER_REPLACEMENT_ASSIGNED",
  CAMPAIGN_TARGET_REACHED = "CAMPAIGN_TARGET_REACHED",
  TRUST_UPDATED = "TRUST_UPDATED",
  REPUTATION_UPDATED = "REPUTATION_UPDATED",
  SYSTEM = "SYSTEM",
  APP_PUBLIC_VERIFIED = "APP_PUBLIC_VERIFIED",
  APP_PUBLIC_STATUS_CHANGED = "APP_PUBLIC_STATUS_CHANGED",
  PREMIUM = "PREMIUM",
  EVIDENCE_SUBMITTED = "EVIDENCE_SUBMITTED",
  EVIDENCE_APPROVED = "EVIDENCE_APPROVED",
  EVIDENCE_REJECTED = "EVIDENCE_REJECTED",
  NEW_RELIABLE_TESTER_ASSIGNED = "NEW_RELIABLE_TESTER_ASSIGNED",
  TESTER_AT_RISK = "TESTER_AT_RISK",
  TESTER_REPLACED = "TESTER_REPLACED",
  NEW_MISSION = "NEW_MISSION",
  DAILY_MISSIONS_AVAILABLE = "DAILY_MISSIONS_AVAILABLE",
  MISSION_DUE = "MISSION_DUE",
  CAMPAIGN_DAY_UPDATE = "CAMPAIGN_DAY_UPDATE",
  CAMPAIGN_ENDED_EARLY = "CAMPAIGN_ENDED_EARLY",
  NEW_CAMPAIGN_AVAILABLE = "NEW_CAMPAIGN_AVAILABLE",
  RELIABILITY_IMPROVED = "RELIABILITY_IMPROVED",
  NEW_OPPORTUNITY = "NEW_OPPORTUNITY",
  PARTICIPATION_VERIFIED = "PARTICIPATION_VERIFIED",
  PARTICIPATION_VERIFICATION_PENDING = "PARTICIPATION_VERIFICATION_PENDING",
  AVAILABILITY_REPORT_RECEIVED = "AVAILABILITY_REPORT_RECEIVED",
  AVAILABILITY_EVIDENCE_REQUESTED = "AVAILABILITY_EVIDENCE_REQUESTED",
  AVAILABILITY_RESOLVED = "AVAILABILITY_RESOLVED",
}

export enum PlayStoreValidationStatus {
  UNKNOWN = "UNKNOWN",
  NOT_FOUND = "NOT_FOUND",
  PRIVATE = "PRIVATE",
  TESTING = "TESTING",
  PUBLIC = "PUBLIC",
  UNAVAILABLE = "UNAVAILABLE",
  ERROR = "ERROR",
}

export enum GoogleGroupValidationStatus {
  UNKNOWN = "UNKNOWN",
  ACCESSIBLE = "ACCESSIBLE",
  REQUIRES_APPROVAL = "REQUIRES_APPROVAL",
  INACCESSIBLE = "INACCESSIBLE",
  INVALID_URL = "INVALID_URL",
}

export enum FraudSignalType {
  EMULATOR_DETECTED = "EMULATOR_DETECTED",
  REPLAY_ATTACK = "REPLAY_ATTACK",
  RAPID_FIRE_EVENTS = "RAPID_FIRE_EVENTS",
  IMPOSSIBLE_TRAVEL = "IMPOSSIBLE_TRAVEL",
  DEVICE_FINGERPRINT_MISMATCH = "DEVICE_FINGERPRINT_MISMATCH",
  AUTOMATED_BEHAVIOR = "AUTOMATED_BEHAVIOR",
  REPEATED_EVIDENCE_HASH = "REPEATED_EVIDENCE_HASH",
  EVIDENCE_REUSE_ACROSS_CAMPAIGNS = "EVIDENCE_REUSE_ACROSS_CAMPAIGNS",
  EXCESSIVE_REJECTED_EVIDENCE = "EXCESSIVE_REJECTED_EVIDENCE",
  IMPOSSIBLE_EVIDENCE_PATTERN = "IMPOSSIBLE_EVIDENCE_PATTERN",
  RAPID_CLAIM_WITHOUT_PARTICIPATION = "RAPID_CLAIM_WITHOUT_PARTICIPATION",
}

export enum InstallationStatus {
  NOT_STARTED = "NOT_STARTED",
  INSTALL_ATTEMPTED = "INSTALL_ATTEMPTED",
  INSTALL_CLAIMED = "INSTALL_CLAIMED",
  INSTALL_DETECTED = "INSTALL_DETECTED",
  FIRST_OPEN = "FIRST_OPEN",
  ACTIVE = "ACTIVE",
  UNVERIFIED = "UNVERIFIED",
  REMOVED = "REMOVED",
}

export enum InstallationVerificationMethod {
  SDK = "SDK",
  PLAY_STORE_FLOW = "PLAY_STORE_FLOW",
  USER_CONFIRMATION = "USER_CONFIRMATION",
  MISSION_ACTIVITY = "MISSION_ACTIVITY",
  EVIDENCE = "EVIDENCE",
}

export enum EvidenceStatus {
  PENDING_REVIEW = "PENDING_REVIEW",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  WITHDRAWN = "WITHDRAWN",
}

export enum EvidenceRejectionReason {
  NOT_VISIBLE = "NOT_VISIBLE",
  WRONG_SCREEN = "WRONG_SCREEN",
  DOES_NOT_MATCH_MISSION = "DOES_NOT_MATCH_MISSION",
  BLURRY = "BLURRY",
  INCOMPLETE = "INCOMPLETE",
  DUPLICATE = "DUPLICATE",
  OTHER = "OTHER",
}

export enum ParticipationStatus {
  UNVERIFIED = "UNVERIFIED",
  PARTIALLY_VERIFIED = "PARTIALLY_VERIFIED",
  VERIFIED = "VERIFIED",
  ACTIVE = "ACTIVE",
  LOW_ACTIVITY = "LOW_ACTIVITY",
  ABANDONED = "ABANDONED",
  COMPLETED = "COMPLETED",
}

export enum AuditAction {
  USER_REGISTERED = "USER_REGISTERED",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  USER_LOGIN = "USER_LOGIN",
  APP_CREATED = "APP_CREATED",
  APP_UPDATED = "APP_UPDATED",
  APP_ARCHIVED = "APP_ARCHIVED",
  CAMPAIGN_CREATED = "CAMPAIGN_CREATED",
  CAMPAIGN_STATE_CHANGED = "CAMPAIGN_STATE_CHANGED",
  CAMPAIGN_STATUS_CHANGED = "CAMPAIGN_STATUS_CHANGED",
  CAMPAIGN_HEALTH_CHANGED = "CAMPAIGN_HEALTH_CHANGED",
  REPLACEMENT_REQUESTED = "REPLACEMENT_REQUESTED",
  MATCHING_EXECUTED = "MATCHING_EXECUTED",
  CAMPAIGN_TESTER_ADDED = "CAMPAIGN_TESTER_ADDED",
  CAMPAIGN_TESTER_REMOVED = "CAMPAIGN_TESTER_REMOVED",
  REFRESH_TOKEN_REVOKED = "REFRESH_TOKEN_REVOKED",
  TESTER_ASSIGNED = "TESTER_ASSIGNED",
  TESTER_ASSIGNMENT_REJECTED = "TESTER_ASSIGNMENT_REJECTED",
  TESTER_REPLACED = "TESTER_REPLACED",
  EXPOSURE_CHANGED = "EXPOSURE_CHANGED",
  MISSION_CREATED = "MISSION_CREATED",
  MISSION_UPDATED = "MISSION_UPDATED",
  MISSION_APPROVED = "MISSION_APPROVED",
  MISSION_REJECTED = "MISSION_REJECTED",
  MISSION_ATTEMPT_STARTED = "MISSION_ATTEMPT_STARTED",
  MISSION_ATTEMPT_SUBMITTED = "MISSION_ATTEMPT_SUBMITTED",
  MISSION_ATTEMPT_VALIDATED = "MISSION_ATTEMPT_VALIDATED",
  MISSION_ATTEMPT_REJECTED = "MISSION_ATTEMPT_REJECTED",
  DIFFICULTY_FEEDBACK_SUBMITTED = "DIFFICULTY_FEEDBACK_SUBMITTED",
  QUALITY_FEEDBACK_SUBMITTED = "QUALITY_FEEDBACK_SUBMITTED",
  REWARD_ISSUED = "REWARD_ISSUED",
  REWARD_GRANTED = "REWARD_GRANTED",
  REWARD_REJECTED = "REWARD_REJECTED",
  REWARD_PENDING = "REWARD_PENDING",
  REWARD_REVIEWED = "REWARD_REVIEWED",
  BALANCE_CHANGED = "BALANCE_CHANGED",
  TRUST_CHANGED = "TRUST_CHANGED",
  TRUST_ADJUSTED = "TRUST_ADJUSTED",
  TRUST_PENALTY_APPLIED = "TRUST_PENALTY_APPLIED",
  TRUST_RECOVERY = "TRUST_RECOVERY",
  FRAUD_EVENT_CREATED = "FRAUD_EVENT_CREATED",
  FRAUD_DECISION_MADE = "FRAUD_DECISION_MADE",
  REPUTATION_CHANGED = "REPUTATION_CHANGED",
  USER_RESTRICTED = "USER_RESTRICTED",
  USER_SUSPENDED = "USER_SUSPENDED",
  USER_BANNED = "USER_BANNED",
  NOTIFICATION_FAILED = "NOTIFICATION_FAILED",
  NOTIFICATION_PREFERENCE_UPDATED = "NOTIFICATION_PREFERENCE_UPDATED",
  DEVICE_TOKEN_REGISTERED = "DEVICE_TOKEN_REGISTERED",
  DEVICE_TOKEN_REVOKED = "DEVICE_TOKEN_REVOKED",
  STORE_VALIDATION_PERFORMED = "STORE_VALIDATION_PERFORMED",
  GROUP_VALIDATION_PERFORMED = "GROUP_VALIDATION_PERFORMED",
  CAMPAIGN_LINKS_TEST_CONFIRMED = "CAMPAIGN_LINKS_TEST_CONFIRMED",
  CAMPAIGN_COMPLETED_OPERATIONS = "CAMPAIGN_COMPLETED_OPERATIONS",
  CAMPAIGN_PUBLIC_VERIFIED = "CAMPAIGN_PUBLIC_VERIFIED",
  INSTALLATION_CLAIMED = "INSTALLATION_CLAIMED",
  INSTALLATION_DETECTED = "INSTALLATION_DETECTED",
  INSTALLATION_VERIFIED = "INSTALLATION_VERIFIED",
  EVIDENCE_SUBMITTED = "EVIDENCE_SUBMITTED",
  EVIDENCE_APPROVED = "EVIDENCE_APPROVED",
  EVIDENCE_REJECTED = "EVIDENCE_REJECTED",
  EVIDENCE_WITHDRAWN = "EVIDENCE_WITHDRAWN",
  PARTICIPATION_VERIFIED = "PARTICIPATION_VERIFIED",
  APP_SDK_STATUS_CHANGED = "APP_SDK_STATUS_CHANGED",
  REPORT_SUBMITTED = "REPORT_SUBMITTED",
  REPORT_DEVELOPER_REVIEWED = "REPORT_DEVELOPER_REVIEWED",
  REPORT_ESCALATED = "REPORT_ESCALATED",
  AI_REVIEW_REQUESTED = "AI_REVIEW_REQUESTED",
  AI_REVIEW_COMPLETED = "AI_REVIEW_COMPLETED",
  AI_REVIEW_FAILED = "AI_REVIEW_FAILED",
  AI_REVIEW_SKIPPED = "AI_REVIEW_SKIPPED",
  AI_BUDGET_EXCEEDED = "AI_BUDGET_EXCEEDED",
  AI_REVIEW_RATE_LIMITED = "AI_REVIEW_RATE_LIMITED",
  REPORT_HUMAN_FINALIZED = "REPORT_HUMAN_FINALIZED",
  REPORT_CLUSTER_CREATED = "REPORT_CLUSTER_CREATED",
  REPORT_CLUSTER_UPDATED = "REPORT_CLUSTER_UPDATED",
  AVAILABILITY_REPORT_CREATED = "AVAILABILITY_REPORT_CREATED",
  AVAILABILITY_REPORT_DUPLICATE = "AVAILABILITY_REPORT_DUPLICATE",
  DEVELOPER_EVIDENCE_REQUESTED = "DEVELOPER_EVIDENCE_REQUESTED",
  DEVELOPER_EVIDENCE_SUBMITTED = "DEVELOPER_EVIDENCE_SUBMITTED",
  AVAILABILITY_REVIEW_STARTED = "AVAILABILITY_REVIEW_STARTED",
  AVAILABILITY_CONFIRMED = "AVAILABILITY_CONFIRMED",
  AVAILABILITY_RESTRICTED = "AVAILABILITY_RESTRICTED",
  AVAILABILITY_UNVERIFIED = "AVAILABILITY_UNVERIFIED",
  AVAILABILITY_RESOLVED = "AVAILABILITY_RESOLVED",
  AVAILABILITY_DISMISSED = "AVAILABILITY_DISMISSED",
  MISSION_BLOCKED_BY_AVAILABILITY = "MISSION_BLOCKED_BY_AVAILABILITY",
  IDENTITY_CREATED = "IDENTITY_CREATED",
  IDENTITY_SIGNAL_DETECTED = "IDENTITY_SIGNAL_DETECTED",
  RISK_SIGNAL_CREATED = "RISK_SIGNAL_CREATED",
  RISK_REVIEW_REQUIRED = "RISK_REVIEW_REQUIRED",
  PROGRESSION_EVALUATED = "PROGRESSION_EVALUATED",
  CAMPAIGN_COMPLETION_COUNTED = "CAMPAIGN_COMPLETION_COUNTED",
  MATCHING_PRIORITY_CALCULATED = "MATCHING_PRIORITY_CALCULATED",
  MATCHING_ASSIGNMENT_CREATED = "MATCHING_ASSIGNMENT_CREATED",
  MATCHING_ASSIGNMENT_REJECTED = "MATCHING_ASSIGNMENT_REJECTED",
  DUPLICATE_PROGRESS_ATTEMPT = "DUPLICATE_PROGRESS_ATTEMPT",
}

export enum IdentityRiskLevel {
  LOW_RISK = "LOW_RISK",
  MEDIUM_RISK = "MEDIUM_RISK",
  HIGH_RISK = "HIGH_RISK",
  REVIEW_REQUIRED = "REVIEW_REQUIRED",
}

export enum SdkIntegrationStatus {
  NOT_CONFIGURED = "NOT_CONFIGURED",
  SDK_ENABLED = "SDK_ENABLED",
  NO_SDK = "NO_SDK",
}

export enum ReportCategory {
  FUNCTIONAL = "FUNCTIONAL",
  UI = "UI",
  PERFORMANCE = "PERFORMANCE",
  CRASH = "CRASH",
  INSTALLATION = "INSTALLATION",
  ACCESSIBILITY = "ACCESSIBILITY",
  SECURITY = "SECURITY",
  OTHER = "OTHER",
}

export enum ReportSeverity {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum ReportStatus {
  SUBMITTED = "SUBMITTED",
  DEVELOPER_REVIEW = "DEVELOPER_REVIEW",
  VALID = "VALID",
  INVALID = "INVALID",
  NEEDS_MORE_EVIDENCE = "NEEDS_MORE_EVIDENCE",
  ESCALATED = "ESCALATED",
  AI_REVIEW_PENDING = "AI_REVIEW_PENDING",
  AI_REVIEWED = "AI_REVIEWED",
  HUMAN_REVIEW = "HUMAN_REVIEW",
  CONFIRMED = "CONFIRMED",
  REJECTED = "REJECTED",
}

export enum DeveloperReportDecision {
  VALID = "VALID",
  INVALID = "INVALID",
  NEEDS_MORE_EVIDENCE = "NEEDS_MORE_EVIDENCE",
  ESCALATED = "ESCALATED",
}

export enum AiReportClassification {
  LIKELY_VALID = "LIKELY_VALID",
  LIKELY_INVALID = "LIKELY_INVALID",
  INCONCLUSIVE = "INCONCLUSIVE",
}

export enum AiRecommendedAction {
  HUMAN_REVIEW = "HUMAN_REVIEW",
  REQUEST_MORE_EVIDENCE = "REQUEST_MORE_EVIDENCE",
  NO_ACTION = "NO_ACTION",
}

export enum HumanReportDecision {
  CONFIRMED = "CONFIRMED",
  REJECTED = "REJECTED",
  NEEDS_MORE_EVIDENCE = "NEEDS_MORE_EVIDENCE",
}

export enum ReportClusterStatus {
  OPEN = "OPEN",
  ESCALATED = "ESCALATED",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
}

export enum AiEscalationDecision {
  HUMAN_REVIEW = "HUMAN_REVIEW",
  COLLECT_MORE_EVIDENCE = "COLLECT_MORE_EVIDENCE",
  AI_CANDIDATE = "AI_CANDIDATE",
  AI_ESCALATION = "AI_ESCALATION",
}

export enum AiAdvisoryRecommendation {
  PROBABLE_VALID = "PROBABLE_VALID",
  PROBABLE_INVALID = "PROBABLE_INVALID",
  NEEDS_MORE_EVIDENCE = "NEEDS_MORE_EVIDENCE",
  HUMAN_REVIEW = "HUMAN_REVIEW",
}

