import { FastifyPluginAsync } from "fastify";

const email = "apexlabssoporte@gmail.com";
const updated = "6 de septiembre de 2026";

function page(title: string, content: string): string {
  return `<!doctype html><html lang="es-419"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>${title} | CallTest</title><style>:root{font-family:system-ui,-apple-system,sans-serif;line-height:1.6;color:#18212f;background:#f7f8fb}body{margin:0}.wrap{max-width:860px;margin:auto;padding:32px 20px 64px}main{background:#fff;padding:32px;border-radius:16px;box-shadow:0 4px 22px #17203314}h1{line-height:1.2}h2{margin-top:2rem}a{color:#3159c6}li{margin:.45rem 0}.notice{padding:14px 16px;border-left:4px solid #3159c6;background:#eef3ff;border-radius:6px}nav{display:flex;flex-wrap:wrap;gap:12px;margin-top:20px}@media(max-width:600px){main{padding:22px 18px;border-radius:0}.wrap{padding:0 0 40px}}</style></head><body><div class="wrap"><main><h1>${title}</h1><p><strong>Última actualización:</strong> ${updated}</p>${content}<hr><p><strong>Contacto legal y de privacidad:</strong> <a href="mailto:${email}">${email}</a></p><nav aria-label="Documentos legales"><a href="/privacy">Privacidad</a><a href="/terms">Términos</a><a href="/community-guidelines">Reglas de la comunidad</a><a href="/account-deletion">Eliminar cuenta</a></nav></main></div></body></html>`;
}

const privacy = `
<p class="notice"><strong>Responsable:</strong> CallTest es operado bajo el nombre comercial ApexLabs Creative. Este aviso integral explica el tratamiento de datos personales en CallTest.</p>
<h2>1. Contacto del responsable</h2><p>Para ejercer derechos o hacer consultas escribe a <a href="mailto:${email}">${email}</a>. La identidad legal completa y el domicilio para recibir notificaciones se incorporarán cuando sean confirmados por el responsable.</p>
<h2>2. Datos tratados</h2><ul><li><strong>Cuenta:</strong> nombre o alias, correo, rol, estado y contraseña almacenada únicamente como hash.</li><li><strong>Campañas:</strong> apps, enlaces de Google Play y Grupos de Google, misiones, asignaciones y progreso.</li><li><strong>Contenido:</strong> comentarios, calificaciones, reportes, datos del dispositivo, pasos de reproducción, evidencias y archivos enviados voluntariamente.</li><li><strong>Técnicos:</strong> modelo de dispositivo, sistema, identificadores de instalación, tokens push, sesiones, fechas, agente de usuario, IP y registros de actividad o errores.</li><li><strong>Seguridad:</strong> hashes de evidencias, señales antifraude, historial de confianza y moderación.</li><li><strong>Progreso:</strong> reputación, XP y Gold internos sin valor monetario.</li></ul><p>No solicitamos datos bancarios, documentos oficiales, salud ni ubicación precisa. No los cargues en evidencias o comentarios.</p>
<h2>3. Finalidades y fundamento</h2><p>Tratamos datos para crear y proteger cuentas; ejecutar campañas y misiones; entregar soporte y notificaciones; revisar evidencias; prevenir fraude; moderar; medir calidad; mantener auditoría; cumplir la ley y defender reclamaciones. El fundamento es prestar el servicio solicitado, cumplir obligaciones, proteger intereses legítimos de seguridad y, cuando proceda, tu consentimiento.</p>
<h2>4. Visibilidad, proveedores y transferencias</h2><p>El desarrollador de una campaña puede ver las evidencias, comentarios, reportes y métricas necesarios para revisarla. No mostramos contraseñas ni señales antifraude internas. No vendemos datos ni hacemos publicidad dirigida.</p><p>Usamos Render (servicio y caché), Neon (base de datos), Cloudflare R2 (evidencias), Google Play y Grupos de Google (acceso a pruebas), y Google Gemini solo para análisis de reportes previamente depurados de datos personales y secretos cuando la función esté activa. Estos proveedores pueden procesar datos fuera de tu país; limitamos el envío a lo necesario y aplicamos medidas técnicas y contractuales razonables.</p>
<h2>5. Conservación</h2><ul><li>Cuenta: mientras esté activa; se anonimiza al eliminarla.</li><li>Evidencias: durante la campaña y hasta 90 días después, salvo controversia u obligación legal.</li><li>Sesiones y refresh tokens: hasta 7 días; tokens push se eliminan con la cuenta.</li><li>Auditoría, seguridad, fraude, confianza y movimientos de puntos: hasta 7 años, anonimizados al eliminar la cuenta.</li></ul>
<h2>6. Derechos y eliminación</h2><p>Puedes solicitar acceso, rectificación, cancelación/eliminación, oposición, limitación, portabilidad o revocación cuando corresponda escribiendo desde el correo asociado a ${email}. Podemos verificar razonablemente la identidad y responderemos en los plazos legales. También puedes eliminar tu cuenta desde la app; consulta el <a href="/account-deletion">procedimiento</a>. Puedes reclamar ante la autoridad de protección de datos competente.</p>
<h2>7. Seguridad</h2><p>Aplicamos cifrado en tránsito, hashes de contraseña, acceso por roles, revocación de sesiones, límites de solicitudes, auditoría y aislamiento de datos. Ningún sistema es infalible; notificaremos incidentes cuando la ley lo exija.</p>
<h2>8. Menores y cambios</h2><p>El servicio es solo para mayores de 18 años. Podemos suspender y eliminar cuentas de menores. Publicaremos aquí los cambios y procuraremos avisar los que sean materiales antes de su vigencia.</p>`;

const terms = `
<p class="notice">Al crear una cuenta o usar CallTest aceptas estos Términos, la Política de Privacidad y las Reglas de la Comunidad.</p>
<h2>1. Elegibilidad y cuenta</h2><p>Debes tener al menos 18 años y capacidad legal. Debes proporcionar información correcta, proteger tus credenciales y avisar accesos no autorizados.</p>
<h2>2. Naturaleza del servicio</h2><p>CallTest es una herramienta independiente para organizar pruebas cerradas de apps Android. No pertenece ni representa a Google. No garantiza aprobación, publicación, posición, reseñas, instalaciones, ingresos ni resultados. Cada desarrollador es responsable de su app, campaña, grupo y cumplimiento legal y de Google Play.</p>
<h2>3. Desarrolladores y testers</h2><p>Los desarrolladores deben tener derechos sobre sus apps y contenido, dar instrucciones legales y seguras, revisar de buena fe y no solicitar reseñas favorables, pagos, compras ni datos sensibles. Los testers deben participar personalmente, sin bots, cuentas duplicadas, actividad falsa o evidencias reutilizadas, y respetar la confidencialidad.</p>
<h2>4. Contenido del usuario</h2><p>Conservas tus derechos. Otorgas a ApexLabs Creative una licencia mundial, no exclusiva, gratuita y limitada para alojar, copiar, procesar y mostrar el contenido únicamente para operar, proteger, moderar y mejorar CallTest y la campaña. Declaras que puedes compartirlo y que no vulnera derechos de terceros.</p>
<h2>5. Uso prohibido</h2><p>Se prohíben fraude, manipulación de métricas o reseñas, malware, suplantación, acoso, discriminación, contenido sexual o violento, infracciones de propiedad intelectual, obtención indebida de datos, ataques o elusión de controles. Aplican las <a href="/community-guidelines">Reglas de la Comunidad</a>.</p>
<h2>6. XP y Gold</h2><p>Son indicadores virtuales sin valor monetario, no canjeables ni transferibles. No son dinero, inversión, criptomoneda, premio financiero ni promesa de pago. Podemos corregirlos por error, fraude o cambios del servicio.</p>
<h2>7. Propiedad intelectual</h2><p>CallTest, su software, diseño y marca están protegidos. Recibes una licencia personal, limitada, revocable, no exclusiva e intransferible para usar el servicio conforme a estos Términos. Las apps y marcas de terceros pertenecen a sus titulares.</p>
<h2>8. Moderación y terminación</h2><p>Podemos retirar contenido, limitar funciones o suspender cuentas por incumplimiento, fraude, riesgo, orden legal o daño. Cuando sea razonable podrás aclararlo escribiendo a ${email}. Puedes eliminar tu cuenta en cualquier momento.</p>
<h2>9. Garantías y responsabilidad</h2><p>El servicio se ofrece “tal cual” y “según disponibilidad”. En la máxima medida legal, no garantizamos disponibilidad ininterrumpida, ausencia total de errores, conservación indefinida ni compatibilidad universal. No respondemos por daños indirectos, pérdida de datos o ingresos, decisiones de Google Play, conducta de usuarios o apps de terceros. La responsabilidad total se limita a lo pagado a CallTest en los 12 meses anteriores o, si fue gratuito, al equivalente de USD 50. Esto no excluye dolo, culpa grave ni derechos irrenunciables.</p>
<h2>10. Indemnidad</h2><p>En la medida permitida, aceptas defender e indemnizar a ApexLabs Creative frente a reclamaciones de terceros causadas por tu app, contenido, campaña, infracción de derechos o uso ilegal. No se reducen derechos irrenunciables de consumidores.</p>
<h2>11. Ley y controversias</h2><p>Antes de reclamar, intentaremos resolver el asunto de buena fe durante 30 días mediante ${email}. Se aplican las leyes de México, sin quitar a consumidores protecciones obligatorias de su residencia. La competencia se determinará conforme a la ley; no imponemos arbitraje donde no sea válido.</p>
<h2>12. General</h2><p>Si una cláusula es inválida, las demás continúan. No puedes ceder tu cuenta. Podemos actualizar estos Términos por cambios legales, técnicos o del servicio y avisaremos los cambios materiales.</p>`;

const community = `<p>Estas reglas forman parte de los Términos.</p><h2>Permitido</h2><ul><li>Pruebas auténticas por personas reales.</li><li>Comentarios honestos, específicos y respetuosos.</li><li>Evidencias pertinentes sin datos innecesarios.</li><li>Reportes de seguridad responsables y privados.</li></ul><h2>Prohibido</h2><ul><li>Comprar, vender o intercambiar reseñas, calificaciones, instalaciones o participación falsa.</li><li>Bots, cuentas múltiples o evidencias duplicadas.</li><li>Solicitar contraseñas, información bancaria, documentos, ubicación precisa o datos de menores.</li><li>Malware, suplantación, acoso, discriminación, explotación sexual, violencia o infracción de derechos.</li><li>Divulgar material confidencial fuera de la campaña.</li></ul><h2>Reportes y medidas</h2><p>Reporta a ${email} con los identificadores necesarios y sin datos excesivos. Podemos investigar, preservar evidencia, retirar contenido y aplicar advertencias, rechazo de evidencias, suspensión o expulsión.</p><h2>Propiedad intelectual</h2><p>Un aviso debe identificar la obra o marca, el contenido cuestionado, contacto, evidencia de titularidad y una declaración de buena fe. Podemos pedir información adicional.</p>`;

const deletion = `<p class="notice">Puedes iniciar la eliminación aunque ya no tengas instalada la app.</p><h2>Desde la app</h2><ol><li>Inicia sesión.</li><li>Abre Cuenta o Perfil.</li><li>Selecciona <strong>Eliminar cuenta</strong> y confirma.</li></ol><h2>Por correo</h2><p>Escribe desde el correo asociado a <a href="mailto:${email}?subject=Eliminar%20mi%20cuenta%20de%20CallTest">${email}</a> con el asunto “Eliminar mi cuenta de CallTest”. Indica solo el correo de la cuenta. Podemos verificar identidad.</p><h2>Qué ocurre</h2><ul><li>Se revocan sesiones y tokens push.</li><li>Nombre, correo, contraseña e identificadores directos se eliminan o anonimizan irreversiblemente.</li><li>Evidencias se eliminan o desvinculan durante la campaña o en un máximo de 90 días, salvo controversia u obligación legal.</li><li>Se solicita la eliminación a proveedores cuando corresponda.</li></ul><h2>Conservación</h2><p>Auditoría, seguridad, fraude y movimientos XP/Gold pueden conservarse anonimizados hasta 7 años para integridad, obligaciones y defensa de reclamaciones. No sirven para reactivar la cuenta ni publicidad.</p><h2>Plazo</h2><p>Procesaremos solicitudes verificadas sin demora indebida y dentro de los plazos legales. Informaremos cualquier retención temporal. La eliminación es permanente.</p>`;

export const legalRoutes: FastifyPluginAsync = async (fastify) => {
  const html = (body: string) => ({ handler: async (_: unknown, reply: { type: (v: string) => { send: (b: string) => unknown } }) => reply.type("text/html; charset=utf-8").send(body) });
  fastify.get("/privacy", html(page("Política de Privacidad", privacy)));
  fastify.get("/terms", html(page("Términos de Uso", terms)));
  fastify.get("/community-guidelines", html(page("Reglas de la Comunidad", community)));
  fastify.get("/account-deletion", html(page("Eliminación de Cuenta", deletion)));
};
